//! Renders the estimation as a config file in JSON5 with comments (spec 5.6).

use super::{Analysis, SheetAnalysis, TableEstimate};
use crate::cell::column_name;

/// Renders the whole config file.
pub(super) fn render(analysis: &Analysis) -> String {
    let file = analysis
        .file
        .file_name()
        .unwrap_or_default()
        .to_string_lossy();
    let mut lines = vec![
        format!("// Generated by `mosty init` from {file}."),
        "// Review the estimated layouts, and fix them if they are wrong.".to_string(),
        "// All row and column indices are 0-origin (e.g., column 0 is A, row 0 is Excel row 1)."
            .to_string(),
        "{".to_string(),
        format!("  id_pattern: {},", quote(&analysis.id_pattern)),
        "  sheets: {".to_string(),
    ];
    lines.extend(analysis.sheets.iter().flat_map(render_sheet));
    lines.extend(["  },".to_string(), "}".to_string(), String::new()]);
    lines.join("\n")
}

/// Renders the entry of a sheet.
fn render_sheet(sheet: &SheetAnalysis) -> Vec<String> {
    let name = quote(&sheet.name);
    let Some(table) = &sheet.table else {
        return vec![format!(
            "    {name}: {{ skip: true }}, // no student ids found"
        )];
    };
    let mut lines = vec![format!("    {name}: {{")];
    lines.extend(
        render_table(table)
            .into_iter()
            .map(|line| format!("      {line}")),
    );
    lines.push("    },".to_string());
    lines
}

/// Renders the keys of a student table with the evidences.
fn render_table(table: &TableEstimate) -> Vec<String> {
    let layout = &table.layout;
    vec![
        format!("id_column: {}, // {}", layout.id_column, id_evidence(table)),
        name_line(table),
        row_line("start_row", layout.start_row),
        row_line("end_row", layout.end_row),
    ]
}

/// Renders `name_column` with the number of names.
fn name_line(table: &TableEstimate) -> String {
    match table.layout.name_column {
        Some(col) => format!(
            "name_column: {col}, // {} (names: {})",
            column_name(col),
            table.names
        ),
        None => "name_column: null, // no names found".to_string(),
    }
}

/// Renders a row key with the Excel row number.
fn row_line(key: &str, row: u32) -> String {
    format!("{key}: {row}, // Excel row {}", row + 1)
}

/// Renders the evidence of the id column, noting the tied columns.
fn id_evidence(table: &TableEstimate) -> String {
    let column = column_name(table.layout.id_column);
    if table.tied_columns.is_empty() {
        return format!("{column} (student ids: {})", table.ids);
    }
    let others: Vec<_> = table
        .tied_columns
        .iter()
        .map(|col| column_name(*col))
        .collect();
    format!(
        "{column} (student ids: {}; CHECK: {} also has the same number)",
        table.ids,
        others.join(", ")
    )
}

/// Quotes the text as a JSON5 string.
fn quote(text: &str) -> String {
    json5::to_string(&text).unwrap_or_else(|_| format!("{text:?}"))
}
